services:
  # postgres Database
  postgres:
    image: docker.io/postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
  # API Server
  api:
    build: ./
    image: docker.io/nirmalkumar1212/simple_blog_api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
    ports:
      - "3000:3000"
